export const ventanas = [
  { nombre:'Trombólisis IV (rtPA / TNK)', inicio:0, fin:4.5, color:'green',
    descripcion:'Ventana clásica desde el último visto normal',
    condicion:'Todos los candidatos sin contraindicaciones absolutas',
    meta:'Door-to-needle ≤ 60 min desde el ingreso',
    referencia:'AHA 2026 — Clase I, Nivel A' },
  { nombre:'Trombectomía — ventana estándar', inicio:0, fin:6, color:'blue',
    descripcion:'Oclusión de gran vaso confirmada por angio-TC',
    condicion:'Carótida interna intracraneal o ACM M1, NIHSS ≥ 6, mRS previo 0–1, ASPECT 3–10',
    meta:'Door-to-puncture ≤ 90 min desde el ingreso',
    cita:'En pacientes con ACV isquémico agudo por OGV de circulación anterior (ACI intracraneal o ACM M1), dentro de las 6 horas del inicio de síntomas, con NIHSS ≥ 6, mRS previo 0–1 y ASPECT 3–10, se recomienda la trombectomía mecánica para mejorar los desenlaces funcionales y reducir la mortalidad.',
    referencia:'AHA 2026 — Clase I, Nivel A' },
  { nombre:'Trombectomía — ventana extendida', tachado:'extendida', inicio:0, fin:24, color:'yellow',
    descripcionPartes: [
      { texto: 'Selección por imagen: TC', tachado: false },
      { texto: ' perfusión o RMN-DWI', tachado: true },
    ],
    condicion:'Estudios DAWN y DEFUSE-3: mismatch clínico-imagen favorable',
    meta:'Definido por imagen, no solo por tiempo',
    tachadoCondicion: true, tachadoMeta: true,
    condicionNueva: 'OGV + ASPECT mayor a 2',
    cita:'En pacientes con ACV isquémico agudo por OGV proximal de circulación anterior (ACI intracraneal o ACM M1), que se presentan entre 6 y 24 horas desde el inicio de síntomas, con NIHSS ≥ 6, mRS previo 0–1 y ASPECT ≥ 6, se recomienda la trombectomía mecánica para mejorar los desenlaces funcionales y reducir la mortalidad.',
    cita2:'★ En pacientes seleccionados con ACV isquémico agudo por OGV proximal de circulación anterior (ACI intracraneal o ACM M1), entre 6 y 24 horas del inicio de síntomas, edad < 80 años, NIHSS ≥ 6, mRS previo 0–1, ASPECT 3–5 y sin efecto de masa significativo en la imagen, se recomienda la trombectomía mecánica para mejorar los desenlaces funcionales y reducir la mortalidad.',
    referencia:'AHA 2026 — Clase I, Nivel A' },
  { nombre:'Trombectomía — Oclusión basilar', inicio:0, fin:24, color:'gray',
    descripcion:'Oclusión de arteria basilar confirmada por angio-TC',
    condicion:'NIHSS ≥ 10, mRS previo 0–1, PC-ASPECTS ≥ 6 (daño isquémico leve)',
    meta:'Decisión urgente — mortalidad muy elevada sin tratamiento',
    cita:'En pacientes con ACV isquémico agudo por oclusión de arteria basilar, mRS previo 0–1, NIHSS ≥ 10 al ingreso y PC-ASPECTS ≥ 6 (daño isquémico leve), la trombectomía mecánica dentro de las 24 horas del inicio de síntomas se recomienda para mejorar el desenlace funcional y reducir la mortalidad.',
    referencia:'AHA 2026 — Clase I' },
  { nombre:'Trombectomía — Large Core Extremo · ventana extendida', inicio:6, fin:24, color:'red',
    descripcion:'Infarto extenso de circulación anterior — ventana extendida, pacientes seleccionados',
    condicion:'ACI intracraneal o ACM M1, edad < 80 años, NIHSS ≥ 6, mRS previo 0–1, ASPECT 0–2, sin efecto de masa significativo',
    meta:'Decisión individualizada con equipo de stroke',
    cita:'★ En pacientes seleccionados con ACV isquémico agudo por OGV proximal de circulación anterior (ACI intracraneal o ACM M1), que se presentan entre 6 y 24 horas desde el inicio de síntomas, edad < 80 años, NIHSS ≥ 6, mRS previo 0–1, ASPECT 0–2 y sin efecto de masa significativo en la imagen, la trombectomía mecánica es razonable para mejorar los desenlaces funcionales y reducir la mortalidad.',
    referencia:'AHA 2026 — Clase IIa' },
  { nombre:'Trombólisis IV — ACV del despertar / inicio indeterminado', inicio:0, fin:4.5, color:'green',
    ventanaTexto: 'Tiempo indeterminado',
    descripcion:'Selección por imagen: mismatch DWI-FLAIR en RMN',
    condicion:'Lesión visible en DWI y ausencia de señal en FLAIR · NIHSS ≥ 4 · mRS previo 0–1 · Sin contraindicaciones estándar',
    meta:'La imagen reemplaza al reloj — el mismatch DWI-FLAIR estima inicio < 4,5 hs',
    cita:'En pacientes con ACV isquémico agudo con tiempo de inicio desconocido o que despiertan con síntomas, con lesión isquémica visible en DWI y ausencia de señal en FLAIR (mismatch DWI-FLAIR), que cumplan los demás criterios de elegibilidad, se recomienda el tratamiento con alteplase IV para mejorar los desenlaces funcionales.',
    referencia:'AHA 2026 — Clase I, Nivel B-R · Ensayo WAKE-UP' },
  { nombre:'Trombólisis IV — ACV del despertar / inicio indeterminado', inicio:0, fin:4.5, color:'green',
    ventanaTexto: 'Tiempo indeterminado',
    descripcion:'Alternativa sin RMN disponible: TC de perfusión con mismatch favorable',
    condicion:'Mismatch clínico-imagen en TC perfusión · NIHSS ≥ 4 · mRS previo 0–1 · Sin contraindicaciones estándar',
    meta:'Usar si RMN no disponible en tiempo aceptable',
    cita:'En pacientes con ACV isquémico agudo de tiempo de inicio desconocido en quienes la RMN no está disponible o no es factible, el mismatch clínico-imagen en TC de perfusión puede utilizarse como criterio alternativo de selección para trombólisis IV.',
    referencia:'AHA 2026 — Clase IIa, Nivel B-NR' },
  { nombre:'Trombectomía — Large Core Extremo', inicio:0, fin:6, color:'red',
    descripcion:'Infarto extenso de circulación anterior — pacientes seleccionados',
    condicion:'ACI intracraneal o ACM M1, edad < 80 años, NIHSS ≥ 6, mRS previo 0–1, ASPECT 0–2, sin efecto de masa significativo',
    meta:'Decisión individualizada con equipo de stroke',
    cita:'★ En pacientes seleccionados con ACV isquémico agudo por OGV proximal de circulación anterior (ACI intracraneal o ACM M1), dentro de las 6 horas del inicio de síntomas, edad < 80 años, NIHSS ≥ 6, mRS previo 0–1, ASPECT 0–2 y sin efecto de masa significativo en la imagen, la trombectomía mecánica es razonable para mejorar los desenlaces funcionales y reducir la mortalidad.',
    referencia:'AHA 2026 — Clase IIa' },
]

export const mensajesVentanas = [
  'Cada 15 min de demora = 1 mes de vida independiente perdido en promedio',
  'La ventana de 24 hs para trombectomía requiere imagen favorable — no aplica a todos',
  'Si califica para ambas: administrar trombólisis Y derivar para trombectomía sin esperar respuesta clínica',
  'El ACV del despertar puede tratarse con mismatch DWI-FLAIR en RMN o imagen de perfusión favorable',
]